# Generated by Django 4.1.1 on 2022-09-27 00:58

import api.utils.upload
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_especified', 'Not especified')], default='not_especified', max_length=15, verbose_name='user gender'),
        ),
        migrations.AlterField(
            model_name='techuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='techuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id(uuid)'),
        ),
        migrations.AlterField(
            model_name='techuser',
            name='identifier_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='user id number'),
        ),
        migrations.AlterField(
            model_name='techuser',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='is validated user'),
        ),
        migrations.AlterField(
            model_name='techuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='techuser',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to=api.utils.upload.get_file_path, verbose_name='user picture'),
        ),
        migrations.AlterField(
            model_name='techuser',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'Administrator'), (2, 'Collaborator'), (3, 'Student')], default=3, verbose_name='user role'),
        ),
    ]
